[package]
name = "milo-excel-helper"
version = "1.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = { version = "1.4.32", features = ["fltk-bundled"] }
rust_xlsxwriter = "0.69.0"
